version: 1
default_environment: dev
project_id: 33577f17-4c64-4c79-8ce7-f7119315663c
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      batch_size: 100000
      database: $TAP_POSTGRES_DATABASE
      host: $TAP_POSTGRES_HOST
      port: $TAP_POSTGRES_PORT
      user: $TAP_POSTGRES_USER
      password: $TAP_PG_PASSWORD
    select:
    - sales-*.*
    - person-*.*
    - purchasing-*.*
    - humanresources-*.*
    - production-*.*
  loaders:
  - name: target-snowflake
    variant: meltanolabs
    pip_url: meltanolabs-target-snowflake
    config:
      account: $TARGET_SNOWFLAKE_ACCOUNT
      database: $TARGET_SNOWFLAKE_DATABASE
      password: $TARGET_SNOWFLAKE_PASSWORD
      role: $TARGET_SNOWFLAKE_ROLE
      user: $TARGET_SNOWFLAKE_USER
      warehouse: $TARGET_SNOWFLAKE_WAREHOUSE
      batch_size_rows: 100000
      add_metadata_columns: true
      insecure_mode: true
      timestamp_column_name: _loaded_at

